[package]
name = "embsinth"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
description = "Embedded systems and integration test harness"

[dependencies]
embsinth-procm = { path = "../procm" }
object = "0.39.1"
probe-rs = { version = "0.32.0", default-features = false, features = [
    "builtin-targets",
    "builtin-formats",
    "coredump",
] }
defmt-decoder = "1.1.0"
defmt-parser = "1.0.0"
dotenvy = "0.15.7"
rzcobs = "0.1.2"
log = "0.4.33"
thiserror = "2.0.19"
anyhow = "1.0.104"
env_logger = "0.11.8"
ignore = "0.4.31"
clap = { version = "4.6.5", features = ["derive"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = { version = "1.0" }
relative-path = { version = "2.0.1", features = ["alloc", "serde"] }
mantra-schema = "0.8"
mantra-macros = { git = "https://github.com/mhatzl/mantra", features = [
    "extract",
] }
